[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
timeout = 300
maxUploadSize = 200

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501 