[theme]
primaryColor = "#007bff"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#212529"
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "auto" 