##########################################
# STREAMLIT SECRETS CONFIGURATION
# Arquivo de credenciais para o projeto Eu na Europa
# ATENÇÃO: Este arquivo contém informações sensíveis
# NÃO COMPARTILHE OU COMITE ESTE ARQUIVO NO GIT!
##########################################

[bitrix]
webhook_url = "https://eunaeuropa.bitrix24.com.br/rest/xxxx/yyyyyyy/" 
user_id = "123456"
access_token = "supersecreto123456789"
webhoook_token = "seu_token_aqui"
bitrix_url = "https://sua-instancia.bitrix24.com"
oauth_client_id = "seu_client_id_aqui"
oauth_client_secret = "seu_client_secret_aqui"

[google]
[google.sheets]
type = "service_account"
project_id = "leitura-planilhas-459604"
private_key_id = "84a6f83793a3000000000000000000000000000"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKj
MzEfYyjiWA4R4/M2bS1GB4t7NXp98C3SC6dVMvDuictGeurT8jNbvJZHtCSuYEvu
NMoSfm76oqFvAp8Gy0iz5sxjZmSnXyCdPEovGhLa0VzMaQ8s+CLOyS56YyCFGeJZ
-----END PRIVATE KEY-----"""
client_email = "dummy-streamlit@leitura-planilhas-459604.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dummy-spreadsheet%40leitura-planilhas-459604.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[google.drive]
# Credenciais para acesso ao Google Drive (se necessário)
api_key = "abcdef123456789"
folder_id = "1ABCdefGHIjklMNOpqrsTUVwxYZ"

[database]
host = "localhost"
user = "admin_user"
password = "super_secure_db_password"
database = "eu_na_europa_production"
port = 3306
ssl_mode = "require"
username = "usuario_db"
name = "nome_db"

[email]
smtp_server = "smtp.office365.com"
smtp_port = 587
username = "notificacoes@eunaeuropa.com.br"
password = "email_password_here"
from_email = "notificacoes@eunaeuropa.com.br"

[azure]
connection_string = "DefaultEndpointsProtocol=https;AccountName=eunaeuropafiles;AccountKey=abcdef123456789;EndpointSuffix=core.windows.net"
storage_account_name = "eunaeuropafiles"
storage_account_key = "abcdef123456789"

[mapbox]
api_key = "pk.eyJxxxxxxxxxxxxxxxxxxxxxxx"

[aws]
access_key_id = "AKIAXXXXXXXXXXXXXXXX"
secret_access_key = "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789"
region = "us-east-1"
bucket_name = "eu-na-europa-files"

# Outras credenciais específicas do projeto
[comune_api]
api_key = "API_KEY_AQUI"
endpoint = "https://api.comune-italiano.org/"

[custom]
# Quaisquer outras configurações específicas que precisem ser secretas
webhook_secret = "secret_key_here"
encryption_key = "encryption_key_here"

# Outras chaves de API (se aplicável)
[apis]
google_maps_key = "sua_chave_google_maps_aqui"

# Chaves para serviços de storage (se aplicável)
[storage]
aws_access_key = "sua_access_key_aqui"
aws_secret_key = "sua_secret_key_aqui"
bucket_name = "nome_do_bucket" 