##########################################
# STREAMLIT SECRETS CONFIGURATION
# Arquivo de credenciais para o projeto Eu na Europa
# ATENÇÃO: Este arquivo contém informações sensíveis
# NÃO COMPARTILHE OU COMITE ESTE ARQUIVO NO GIT!
##########################################

[bitrix]
webhook_url = "https://eunaeuropa.bitrix24.com.br/rest/xxxx/yyyyyyy/" 
user_id = "123456"
access_token = "supersecreto123456789"

[google]
[google.sheets]
type = "service_account"
project_id = "leitura-planilhas-459604"
private_key_id = "84a6f83793a3xxxxxxxxxxxxxxxxxxxx"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxxxxxxxxxxx
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
... (chave completa aqui) ...
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
-----END PRIVATE KEY-----"""
client_email = "conta-de-servico@leitura-planilhas-459604.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/conta-de-servico%40leitura-planilhas-459604.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[google.drive]
# Credenciais para acesso ao Google Drive (se necessário)
api_key = "abcdef123456789"
folder_id = "1ABCdefGHIjklMNOpqrsTUVwxYZ"

[database]
host = "eu-na-europa-db.mysql.database.azure.com"
user = "admin_user"
password = "super_secure_db_password"
database = "eu_na_europa_production"
port = 3306
ssl_mode = "require"

[email]
smtp_server = "smtp.office365.com"
smtp_port = 587
username = "notificacoes@eunaeuropa.com.br"
password = "email_password_here"
from_email = "notificacoes@eunaeuropa.com.br"

[azure]
connection_string = "DefaultEndpointsProtocol=https;AccountName=eunaeuropafiles;AccountKey=abcdef123456789;EndpointSuffix=core.windows.net"
storage_account_name = "eunaeuropafiles"
storage_account_key = "abcdef123456789"

[mapbox]
api_key = "pk.eyJxxxxxxxxxxxxxxxxxxxxxxx"

[aws]
access_key_id = "AKIAXXXXXXXXXXXXXXXX"
secret_access_key = "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789"
region = "us-east-1"
bucket_name = "eu-na-europa-files"

# Outras credenciais específicas do projeto
[comune_api]
api_key = "API_KEY_AQUI"
endpoint = "https://api.comune-italiano.org/"

[custom]
# Quaisquer outras configurações específicas que precisem ser secretas
webhook_secret = "secret_key_here"
encryption_key = "encryption_key_here" 