##########################################
# STREAMLIT SECRETS CONFIGURATION
# Arquivo de credenciais para o projeto Eu na Europa
# ATENÇÃO: Este arquivo contém informações sensíveis
# NÃO COMPARTILHE OU COMITE ESTE ARQUIVO NO GIT!
##########################################

[bitrix]
webhook_url = "https://eunaeuropa.bitrix24.com.br/rest/xxxx/yyyyyyy/"
user_id = "123456"
access_token = "supersecreto123456789"
BITRIX_URL = "https://eunaeuropacidadania.bitrix24.com.br"
BITRIX_TOKEN = "WPuNlYiO1V3VV4BMaw47YAgyU4zVus7sbr"

[google]
[google.sheets]
type = "service_account"
project_id = "leitura-planilhas-459604"
private_key_id = "84a6f83793a3f0a503b349b4682662effeb1bbca"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC9yDXKDe04RhB+
+vqOpbiUg3RQGKdpnMMCIj8ZoW6poV4yX6XMOO8p+9bSW/vT+hDqQq2K9xwuz3MQ
PbTr9zPhy/7r2yiC8M/T/JZR4YaIj/PwWimlkZYDgCl2i5emrIBjCEr/tEzTGQTO
e2r6KKBJduC3qzK7w9MNk/INqMOP7cat5zRR4Rva9QBlxAGhIYYYwUW2sU+QkEeT
MVq9nVJsKqCwzRy6WxHkroZ0sxNr+3pTCuvRl0vCQicbVp3V/WuI+Nzfefm7VvOp
sAtQ2IHH6yFTHN5qulEL/7fMDAwR0hKItje6ej1LoE5MbqBzuNgKjwVc99ilhoUk
LfuzECOnAgMBAAECggEANjvnRzkon+rB3w/JF4e7UlGopRUOjotaXRs9Tg1IixhO
y3Vy84QXsLdD4jSgKCkvuUpZvrs0ZhophywjLkWkIXRDAtLL5nN76NgnevnIkPEW
ZIrXmPWcWZ6/+p0UtvBX9jUR/bXgOHlPWtSBM0D14VikCkjVxDvHbftn8khWrqPm
FqHBEJZrw6qy7KmSMF1HhllVGakqdMUPtwaqLKN5tfmd1XEXpA+fdlmaf991LbdI
ClpffbX6qiQo7y09jlg5jVrkiAM5lwz6hmrAZ+JLR9bLpUG+piq/bLlNi8Y12bpq
RWEnKv0gjsroo1wnVwC2cuVT7W97SiWBLJRjcCUT6QKBgQDjgykS34tTAIn2w8hh
q30Ls4+XA28HbnxmMX2KoVCFrLxh+9vBMG439LGlXhb+nTtCdRdh1FO8GG0Qjpvj
KUvTDSBjmVGoe7TjQpQ5+t8sHHP+wzsw4ocugSJT9Usz8gU5dx+YzHCaLpfL00zt
C5JNnS3QMu3kwQsUqMjXvlnLmQKBgQDVi536fDtNizvrWBhb78WngFJ5neI/ocJ2
DukuSu4FXZAbDqdMOjX1rdeznKKIR/DZW46YdPF8we0ofhZnb53kpzmWNK9b4tjO
soDMyD5/YQJeIz+lkG/NtoU/oO2WiMnHfIBk9Se41aW2BawhhbBFMvfgcKr6NLHZ
7++pdCzxPwKBgQDS4kGRP+o5vpcjR2iWt8lJrl/bf5BL2Cqw4xDWDh7AOVPIkxao
JMcVUNfVS7iOu5kxSa2pvZD8GbwGi9mNHzssXs914qihPkF2IcGZWKPClIEkVTyp
XGAnSAVUw1q4xI35LST5kg6Rq7yCbtKwKnirPpU3le2SiylFNgosiEFdiQKBgQCS
qeBnj/le6bjOi2O3iPc0cpKyinhAgcXANb97FuVg9ACsRKUsWnKC+NHDv1l1xgsq
DZLjLLZKnBpZDDgw9Fz6FMwdWLPzpNqJI9oIS6N48tSgeQ8WlBvlqmzb5ZgoImyL
QPwh2qpcbQfx+vVc1Kfa7wWFtXwIejaIWx08Qdk4GwKBgQDHB6DFAipJEokI/Q73
8Wn2wWYgU0seMpKv576JLer6PCpcnqnQg2ne2nS6BU57/mqUyfjMuey8U4dRSNrH
YKcpcLfwqHZDB0+vZ5r04hD/Ogi9OBDXjoF9Mep04qbR8x22osVpqEcXRJHGSn57
oYCn+C0IGQr7p96eSvL93noOMw==
-----END PRIVATE KEY-----"""
client_email = "leitura-planilhas@leitura-planilhas-459604.iam.gserviceaccount.com"
client_id = "112984526573485256434"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/leitura-planilhas%40leitura-planilhas-459604.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[google.drive]
# Credenciais para acesso ao Google Drive (se necessário)
api_key = "abcdef123456789"
folder_id = "1ABCdefGHIjklMNOpqrsTUVwxYZ"

[supabase]
url = "https://mdjrgbclsayzvnniwarj.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kanJnYmNsc2F5enZubml3YXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzAwMzcsImV4cCI6MjA2MzUwNjAzN30.OnkJQJT4ycBIqFodIf5OhJ8DOK8He1oye4T7XyBDcEE"   
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kanJnYmNsc2F5enZubml3YXJqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzkzMDAzNywiZXhwIjoyMDYzNTA2MDM3fQ.K6LSmjhEyXH-HxnKqsMCZ4LRpdGtrVJi6Txz-xeHEQg" 